imports:
    - { resource: tables.yml }
    - { resource: cron_tasks.yml }

services:
    auth:
        class: phpbb_auth

    cache:
        class: phpbb_cache_service
        arguments:
             - @cache.driver

    cache.driver:
        class: %cache.driver.class%

    cache.driver.install:
        class: phpbb_cache_driver_file

    class_loader:
        class: phpbb_class_loader
        arguments:
            - phpbb_
            - %core.root_path%includes/
            - .%core.php_ext%
        calls:
            - [register, []]
            - [set_cache, [@cache.driver]]

    class_loader.ext:
        class: phpbb_class_loader
        arguments:
            - phpbb_ext_
            - %core.root_path%ext/
            - .%core.php_ext%
        calls:
            - [register, []]
            - [set_cache, [@cache.driver]]

    config:
        class: phpbb_config_db
        arguments:
            - @dbal.conn
            - @cache.driver
            - %tables.config%

    cron.task_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container

    cron.manager:
        class: phpbb_cron_manager
        arguments:
            - @cron.task_collection
            - %core.root_path%
            - %core.php_ext%

    cron.lock_db:
        class: phpbb_lock_db
        arguments:
            - cron_lock
            - @config
            - @dbal.conn

    dispatcher:
        class: phpbb_event_dispatcher
        arguments:
            - @service_container

    dbal.conn:
        class: %dbal.driver.class%
        calls:
            - [sql_connect, [%dbal.dbhost%, %dbal.dbuser%, %dbal.dbpasswd%, %dbal.dbname%, %dbal.dbport%, false, %dbal.new_link%]]

    dbal.tools:
        file: %core.root_path%includes/db/db_tools.%core.php_ext%
        class: phpbb_db_tools
        arguments:
            - @dbal.conn

    event.subscriber_loader:
        class: phpbb_event_extension_subscriber_loader
        arguments:
            - @dispatcher
            - @ext.manager
        calls:
            - [load, []]

    ext.manager:
        class: phpbb_extension_manager
        arguments:
            - @dbal.conn
            - @config
            - %tables.ext%
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver

    migrator:
        class: phpbb_db_migrator
        arguments:
            - @service_container
            - @migrator.tool_collection

    migrator.tool_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container

    migrator.tool.config:
        class: phpbb_db_migration_tool_config
        arguments:
            - @config
        tags:
            - { name: migrator:tool }

    migrator.tool.module:
        class: phpbb_db_migration_tool_module
        arguments:
            - @dbal.conn
            - @cache
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: migrator:tool }

    migrator.tool.permission:
        class: phpbb_db_migration_tool_permission
        arguments:
            - @dbal.conn
            - @cache
            - @auth
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: migrator:tool }

    request:
        class: phpbb_request

    style:
        class: phpbb_style
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @user
            - @style.resource_locator
            - @style.path_provider_ext
            - @template

    style.resource_locator:
        class: phpbb_style_resource_locator

    style.path_provider_ext:
        class: phpbb_style_extension_path_provider
        arguments:
            - @ext.manager
            - @style.path_provider

    style.path_provider:
        class: phpbb_style_path_provider

    template:
        class: phpbb_template
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @user
            - @style.resource_locator
            - @template_context

    template_context:
        class: phpbb_template_context

    user:
        class: phpbb_user
